### PR TITLE
Fix browse not returning to selected tab

### PR DESCRIPTION
**Pull request by gfjardim**

### CODE REVIEW

**Comment by dlandon** [comment]
How do I implement the cookie in the pages?

**Comment by gfjardim** [comment]
This code will be loaded in every page, but will run only when Browse is opened by RecycleBin. Pretty much the same code I used in UD.

**Comment by dlandon** [comment]
I had to rename it RecycleBinAppend.page and it seems to work.

**Comment by dlandon** [comment]
Works, but not always consistent.  If I browse up the file tree and then click 'Done', it doesn't always return to he proper tab.

**Pull request merged**
